a = int(input("Enter the number"))
b = int(input("Enter the number"))
print("addition is")
print(a+b)
print("Subtraction is")
print(a-b)
print("multiplication is")
print(a*b)
print("Division is")
print(a/b)
